version: 0.0.1.{build}

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

init:
  - git config --global core.autocrlf true

before_build:
  - choco install -y curl InnoSetup
  - set PATH="C:\Program Files\7-Zip";%PATH%
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
  - set PATH=C:\Python27\Scripts;%PATH%
  - git clone https://github.com/moteus/lua-spylog-installer installer

build_script:
  - cd .\installer\win
  - iscc spylog.iss /O"%APPVEYOR_BUILD_FOLDER%" /DArch=x86 /DLuaVer=5.1 /DSpyLogGit=..\..
  - iscc spylog.iss /O"%APPVEYOR_BUILD_FOLDER%" /DArch=x64 /DLuaVer=5.1 /DSpyLogGit=..\..

artifacts:
  - path: SpyLog-x86*.exe
    name: SpyLog-x86

  - path: SpyLog-x64*.exe
    name: SpyLog-x64

deploy:
  - provider: GitHub
    auth_token:
      secure: quhtxEmz8RrBAwBB5rZ675IUuhqjiDxTNouM5rEnUTeT7Gj3Lr4qPxuRcF60dqzW
    artifact: SpyLog-x86,SpyLog-x64
    draft: false
    prerelease: true
    on:
      appveyor_repo_tag: true
